root: true
env:
  es6: true
  node: true
  browser: true
parser: babel-eslint
parserOptions:
  emcaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
extends:
- eslint:recommended
- plugin:prettier/recommended
- plugin:react/recommended
plugins:
- import
rules:
  no-console: off
  react/prop-types: off
