AllCops:
  Exclude:
    - bin/*
    - db/schema.rb

Rails:
  Enabled: true

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false
