AllCops:
  TargetRubyVersion: 2.4
  Include:
    - .git-hooks/**/*.rb
  Exclude:
    - bin/*
    - db/schema.rb

Rails:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Naming/FileName:
  Exclude:
    - Gemfile
    - Rakefile
