options:
  formatter: stylish
  merge-default-rules: true
files:
  ignore:
    - node_modules/**/*
rules:
  class-name-format: 0
  leading-zero: 0
  no-trailing-zero: 0
  no-url-domains: 0
  no-url-protocols: 0
  placeholder-in-extend: 0
  property-sort-order:
    - 1
    - order: concentric # https://github.com/sasstools/sass-lint/blob/develop/lib/config/property-sort-orders/concentric.yml
  quotes:
    - 1
    - style: double
  variable-name-format: 0
