options:
  formatter: stylish
  merge-default-rules: true
files:
  ignore:
    - node_modules/**/*
rules:
  property-sort-order: 0
  class-name-format: 0
  variable-name-format: 0
  quotes:
    - 1
    - style: double
  leading-zero: 0
  no-trailing-zero: 0
  placeholder-in-extend: 0
  no-url-domains: 0
  no-url-protocols: 0
